//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFML.Properties {
    using global::System;
    using global::System.Reflection;

    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("global::System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static global::System.Drawing.Bitmap WindowsLight {
            get {
                object obj = ResourceManager.GetObject("WindowsLight", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static global::System.Drawing.Bitmap WindowsDark {
            get {
                object obj = ResourceManager.GetObject("WindowsDark", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static global::System.Drawing.Bitmap MintYLight {
            get {
                object obj = ResourceManager.GetObject("MintYLight", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static global::System.Drawing.Bitmap MintYDark {
            get {
                object obj = ResourceManager.GetObject("MintYDark", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] Font {
            get {
                object obj = ResourceManager.GetObject("Font", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
